import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import BlockIcon from '@mui/icons-material/Block';
import DownloadIcon from '@mui/icons-material/Download';
import SendIcon from '@mui/icons-material/Send';
import { Alert, Box, Button, Grid, Paper, Snackbar, Stack, Typography } from '@mui/material';
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import ErrorMessage from '../../components/common/ErrorMessage';
import Loader from '../../components/common/Loader';
import PageHeader from '../../components/common/PageHeader';
import LetterPreview from '../../components/letters/LetterPreview';
import LetterStatusChip from '../../components/letters/LetterStatusChip';
import LetterTypeChip from '../../components/letters/LetterTypeChip';
import { letterService } from '../../services/letterService';
import { formatDate, formatTime } from '../../utils/dateUtils';

const Detail = ({ label, value }) => (
  <Grid item xs={12} sm={6} md={4}>
    <Typography variant="body2" color="text.secondary">{label}</Typography>
    <Typography sx={{ fontWeight: 700 }}>{value || '-'}</Typography>
  </Grid>
);

const LetterDetails = ({ admin = false }) => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [letter, setLetter] = useState(null);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState(false);
  const [error, setError] = useState('');
  const [snackbar, setSnackbar] = useState({ open: false, message: '', severity: 'success' });

  const backPath = admin ? '/admin/letters' : '/hr/letters';

  useEffect(() => {
    let mounted = true;
    letterService.getLetterById(id)
      .then((record) => mounted && setLetter(record))
      .catch((letterError) => mounted && setError(letterError.message))
      .finally(() => mounted && setLoading(false));
    return () => {
      mounted = false;
    };
  }, [id]);

  const runAction = async (action, successMessage) => {
    setActionLoading(true);
    try {
      const updatedLetter = await action();
      if (updatedLetter) setLetter(updatedLetter);
      setSnackbar({ open: true, message: successMessage, severity: 'success' });
    } catch (actionError) {
      setSnackbar({ open: true, message: actionError.message, severity: 'error' });
    } finally {
      setActionLoading(false);
    }
  };

  return (
    <Box>
      <PageHeader
        title="Letter Details"
        subtitle="Preview the generated letter and manage sending/status."
        actions={<Button startIcon={<ArrowBackIcon />} onClick={() => navigate(backPath)}>Back</Button>}
      />
      <ErrorMessage message={error} />
      {loading ? (
        <Loader />
      ) : letter ? (
        <Stack spacing={3}>
          <Paper elevation={0} sx={{ p: 3, border: '1px solid', borderColor: 'divider', borderRadius: 2 }}>
            <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={2} sx={{ mb: 3 }}>
              <Box>
                <Typography variant="h5" sx={{ fontWeight: 850 }}>{letter.candidateName}</Typography>
                <Typography color="text.secondary">{letter.candidateEmail}</Typography>
              </Box>
              <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>
                <LetterTypeChip type={letter.letterType} />
                <LetterStatusChip status={letter.status} />
              </Stack>
            </Stack>
            <Grid container spacing={2.5}>
              <Detail label="Role" value={letter.roleName} />
              <Detail label="Department" value={letter.department} />
              <Detail label="Company" value={letter.companyName} />
              <Detail label="Joining date" value={formatDate(letter.joiningDate)} />
              <Detail label="Internship start" value={formatDate(letter.internshipStartDate)} />
              <Detail label="Internship end" value={formatDate(letter.internshipEndDate)} />
              <Detail label="Stipend" value={letter.stipend ? `Rs. ${letter.stipend}` : '-'} />
              <Detail label="Generated by" value={letter.generatedByName} />
              <Detail label="Sent at" value={letter.sentAt ? `${formatDate(letter.sentAt)} ${formatTime(letter.sentAt)}` : '-'} />
            </Grid>
            <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap sx={{ mt: 3 }}>
              <Button variant="contained" startIcon={<SendIcon />} disabled={actionLoading || letter.status === 'SENT'} onClick={() => runAction(() => letterService.sendLetter(letter.id), 'Letter sent successfully.')}>Send</Button>
              <Button startIcon={<DownloadIcon />} onClick={() => runAction(async () => { await letterService.downloadLetter(letter.id); return null; }, 'Letter opened for download.')}>Download</Button>
              <Button color="error" startIcon={<BlockIcon />} disabled={actionLoading || letter.status === 'CANCELLED'} onClick={() => runAction(() => letterService.updateLetterStatus(letter.id, { status: 'CANCELLED' }), 'Letter cancelled.')}>Mark Cancelled</Button>
            </Stack>
          </Paper>
          <LetterPreview letter={letter} onCopy={(text) => navigator.clipboard.writeText(text).then(() => setSnackbar({ open: true, message: 'Letter text copied.', severity: 'success' }))} />
        </Stack>
      ) : null}
      <Snackbar open={snackbar.open} autoHideDuration={3500} onClose={() => setSnackbar((current) => ({ ...current, open: false }))}>
        <Alert severity={snackbar.severity} variant="filled">{snackbar.message}</Alert>
      </Snackbar>
    </Box>
  );
};

export default LetterDetails;
